# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-12 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=32, verbose_name='主机IP')),
                ('host_os', models.CharField(max_length=64, verbose_name='主机系统')),
                ('host_partition', models.CharField(max_length=64, verbose_name='磁盘分区')),
                ('record_time', models.DateTimeField(default=datetime.datetime(2019, 5, 12, 20, 25, 40, 113885), verbose_name='录入时间')),
                ('operator', models.CharField(max_length=64, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '主机记录',
                'verbose_name_plural': '主机记录',
            },
        ),
    ]
