# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostrecord',
            name='record_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='录入时间'),
        ),
    ]
